name = "rss-discord-bot"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 15分間隔でRSSチェックを実行（Phase 2で使用）
# [triggers]
# crons = ["*/15 * * * *"]

# KV Namespaceの設定
[[kv_namespaces]]
binding = "RSS_STORAGE"
id = "2b68d688086c42278caa6010fcead223"      # 本番用KV namespace ID
preview_id = "65960b9a4a584fe5ba9d9b6692b717e8" # プレビュー用KV namespace ID

# 環境変数（シークレット）の設定
# 以下のコマンドで設定してください:
# wrangler secret put DISCORD_BOT_TOKEN
# wrangler secret put DISCORD_APPLICATION_ID
# wrangler secret put DISCORD_PUBLIC_KEY
# wrangler secret put DISCORD_WEBHOOK_URL

[vars]
# 開発用の環境変数（プレーンテキスト）
ENVIRONMENT = "development"
