name = "rss-discord-bot"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 15分間隔でRSSチェックを実行
[triggers]
crons = ["*/15 * * * *"]

# KV Namespaceの設定
# 使用方法:
# 1. Cloudflare DashboardでKV Namespaceを作成
# 2. このファイルをwrangler.tomlにコピー
# 3. 実際のNamespace IDに置き換え
[[kv_namespaces]]
binding = "RSS_STORAGE"
id = "your_production_kv_namespace_id_here"
preview_id = "your_preview_kv_namespace_id_here"

# 環境変数（シークレット）の設定
# 以下のコマンドで設定してください:
# wrangler secret put DISCORD_BOT_TOKEN
# wrangler secret put DISCORD_APPLICATION_ID
# wrangler secret put DISCORD_PUBLIC_KEY
# wrangler secret put DISCORD_WEBHOOK_URL

[vars]
# 開発用の環境変数（プレーンテキスト）
ENVIRONMENT = "development"
